# Generated by Django 4.1.2 on 2022-10-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartas',
            fields=[
                ('idbiblioteca', models.IntegerField(primary_key=True, serialize=False, verbose_name='IDBIBLIOTECA')),
                ('juego', models.CharField(default='Juego', max_length=50, verbose_name='JUEGO')),
                ('sets', models.CharField(default='Sets', max_length=50, verbose_name='SETS')),
                ('idcarta', models.IntegerField(default=0, verbose_name='IDCARTA')),
                ('nombrecarta', models.CharField(default='Nombre Carta', max_length=50, verbose_name='NOMBRECARTA')),
                ('habilidad', models.CharField(default='Habilidad', max_length=250, verbose_name='HABILIDAD')),
                ('keyword', models.CharField(default='Keyword', max_length=50, verbose_name='KEYWORD')),
                ('costomana', models.IntegerField(default=0, verbose_name='COSTOMANA')),
                ('fuerza', models.IntegerField(default=0, verbose_name='FUERZA')),
                ('salud', models.IntegerField(default=0, verbose_name='SALUD')),
                ('rareza', models.CharField(default='Rareza', max_length=50, verbose_name='RAREZA')),
                ('tipocarta', models.CharField(default='Tipo carta', max_length=50, verbose_name='TIPOCARTA')),
                ('region', models.CharField(default='Region', max_length=50, verbose_name='REGION')),
                ('tipohechizo', models.CharField(default='Tipo hechizo', max_length=50, verbose_name='TIPOHECHIZO')),
            ],
            options={
                'verbose_name_plural': 'Cartas',
            },
        ),
    ]
